import Head from 'next/head';
import { useMemo } from 'react';
import { useRecoilValue } from 'recoil';
import { languageAtom } from '../atoms';

import styles from '../styles/Home.module.css';

import { Navbar, Intro, Info, Program, Speakers, Footer } from '../components';

import { textsRU, textsKZ, textsGER } from '../i18n';

export default function Home() {
	const language = useRecoilValue(languageAtom);
	const texts = useMemo(() => {
		switch (language) {
			case 1:
				return textsKZ;
			case 2:
				return textsGER;
			case 0:
			default:
				return textsRU;
		}
	}, [language]);

	return (
		<div className={styles.container}>
			<Head>
				<title>Деловые связи 2022</title>
				<meta name="description" content="Generated by create next app" />
				{/* <link rel="icon" href="/favicon.ico" /> */}
				<link rel="icon" href="/favicon.png" />
			</Head>

			<Navbar texts={{ ...texts.global, ...texts.navbar }} />

			<Intro texts={{ ...texts.global, ...texts.intro }} />
			<Info texts={{ ...texts.global, ...texts.info }} />
			<Program texts={{ ...texts.global, ...texts.program }} />
			<div className={styles.videoWrap}>
				{language === 0 && (
					<video className={styles.video} muted controls>
						<source src="/video/v_ru.mp4" type="video/mp4" />
						Your browser does not support the video tag.
					</video>
				)}
				{language === 1 && (
					<video className={styles.video} muted controls>
						<source src="/video/v_kz.mp4" type="video/mp4" />
						Your browser does not support the video tag.
					</video>
				)}
				{language === 2 && (
					<video className={styles.video} muted controls>
						<source src="/video/v_kz.mp4" type="video/mp4" />
						Your browser does not support the video tag.
					</video>
				)}
			</div>
			<Speakers texts={{ ...texts.global, ...texts.speakers }} />

			<Footer texts={{ ...texts.global, ...texts.footer }} />
		</div>
	);
}
